### ISSUE TITLE
Installation not possible: Cannot find module replace.js

### ISSUE THREAD

**Issue by tonqa** [oasp/oasp4js#23]
If I currently check out the main branch of this project, the build with 'npm install' succeeds, but then I get this error below when typing 'gulp serve'. This makes it impossible for me to develop extensions to OASP/Devon. Can you please help me with this one?

PS C:\dev\oasp4js> gulp serve
[16:23:43] Using gulpfile C:\dev\oasp4js\gulpfile.js
[16:23:43] Starting 'sync group4:0'...
[16:23:43] Starting 'wiredep'...
[16:23:43] Starting 'sync group1:0'...
[16:23:43] Starting 'ngTemplatesTasksGeneration'...
[16:23:43] Finished 'ngTemplatesTasksGeneration' after 3.49 ms
[16:23:43] Finished 'sync group1:0' after 7.15 ms
[16:23:43] Starting 'sync group1:1'...
[16:23:43] Starting 'ngTemplates[main.templates.js]'...
[16:23:44] 'ngTemplates[main.templates.js]' errored after 67 ms
[16:23:44] Error: Cannot find module 'C:\dev\oasp4js\custom\replace.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at null.<anonymous> (C:\dev\oasp4js\node_modules\gulp-processhtml\node_modules\htmlprocessor\lib\htmlprocessor.js:1
06:7)
    at Array.forEach (native)
    at new HTMLProcessor (C:\dev\oasp4js\node_modules\gulp-processhtml\node_modules\htmlprocessor\lib\htmlprocessor.js:
105:35)
    at Object.module.exports (C:\dev\oasp4js\node_modules\gulp-processhtml\index.js:15:21)
    at Gulp.<anonymous> (C:\dev\oasp4js\gulp\build.js:16:25)
    at module.exports (C:\dev\oasp4js\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
[16:23:44] Finished 'wiredep' after 437 ms

**Comment by MarcoRose** [comment]
Never came up again
