### ISSUE TITLE
gulp build fails

### ISSUE THREAD

**Issue by RobusK** [oasp/oasp4js#42]
C:\tmp\oasp4js>gulp
[11:52:14] Using gulpfile C:\tmp\oasp4js\gulpfile.js
[11:52:14] Starting 'clean'...
[11:52:14] Finished 'clean' after 6.18 ms
[11:52:14] Starting 'default'...
[11:52:14] Starting 'build:dist'...
[11:52:14] Starting 'wiredep'...
[11:52:14] Starting 'sync group1:0'...
[11:52:14] Starting 'ngTemplatesTasksGeneration'...
[11:52:14] Finished 'ngTemplatesTasksGeneration' after 2.14 ms
[11:52:14] Finished 'sync group1:0' after 3.75 ms
[11:52:14] Starting 'sync group1:1'...
[11:52:14] Starting 'ngTemplates[main.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-mock.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-security.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-ui.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-i18n.templates.js]'...
[11:52:14] Starting 'ngTemplates[offer-mgmt.templates.js]'...
[11:52:14] Starting 'ngTemplates[sales-mgmt.templates.js]'...
[11:52:14] Starting 'ngTemplates[table-mgmt.templates.js]'...
[11:52:14] Starting 'sprite'...
[11:52:14] Starting 'less'...
[11:52:14] Starting 'html'...
[11:52:14] Starting 'img'...
[11:52:15] Starting 'i18n'...
[11:52:15] Starting 'fonts'...
[11:52:15] Finished 'build:dist' after 1.14 s
[11:52:15] Finished 'default' after 1.14 s
C:\tmp\oasp4js\node_modules\gulp-ng-templates\node_modules\gulp-header\index.js:
58
    var file = _file.clone({ contents: false });
                    ^
TypeError: Cannot read property 'clone' of undefined
    at DestroyableTransform.EndStream [as _flush] (C:\tmp\oasp4js\node_modules\g
ulp-ng-templates\node_modules\gulp-header\index.js:58:21)
    at DestroyableTransform.<anonymous> (C:\tmp\oasp4js\node_modules\through2\no
de_modules\readable-stream\lib\_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:104:17)
    at prefinish (C:\tmp\oasp4js\node_modules\through2\node_modules\readable-str
eam\lib\_stream_writable.js:492:12)
    at finishMaybe (C:\tmp\oasp4js\node_modules\through2\node_modules\readable-s
tream\lib\_stream_writable.js:500:7)
    at endWritable (C:\tmp\oasp4js\node_modules\through2\node_modules\readable-s
tream\lib\_stream_writable.js:512:3)
    at DestroyableTransform.Writable.end (C:\tmp\oasp4js\node_modules\through2\n
ode_modules\readable-stream\lib\_stream_writable.js:477:5)
    at DestroyableTransform.onend (C:\tmp\oasp4js\node_modules\gulp-concat\node_
modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)

C:\tmp\oasp4js>

seems to stem from a dependency update, related issue/fix I've found:
https://github.com/google/material-design-lite/commit/618c51fbfa1989d4e99114fe4c78d9d20b707cef

**Comment by RobusK** [comment]
After further investigation, omitting the ngTemplates task resolves the issue

**Comment by may-bee** [comment]
depends on https://github.com/tracker1/gulp-header/issues/21
Currently, I am trying to fix the dependency versions to not upgrade to any incompatible dependency in future.

**Comment by RobusK** [comment]
I was able to resolve the issue by including the following file as npm-shrinkwrap.json in a project based on oasp4js:
http://pastebin.com/BjmZTzAT

**Comment by may-bee** [comment]
Seemingly, I could also resolve this issue.
Furthermore, I will make the dependency configuration more stable to prevent from such automatic upgrade problems in future. I will issue a pull request soon.

**Comment by may-bee** [comment]
fixed due to the latest release of gulp-header.
Nevertheless, someone should have a look at the PR and merge it.
