### ISSUE TITLE
update released cross-cutting oasp modules

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4js#93]
We already have a bower repository for our oasp modules: oasp/oasp4js-bower
However, for resolving the typescript migration in #80, we first should use our oasp modules like any other application will do. Thus, we can ignore the migration of the modules for now and suspend it to a later point in time.

Furthermore, please consider the discussion in #91.
@mmatczak: 
1. is there any documentation how to release the modules in the bower repository?
2. do we have to change anything to make the modules also available for npm?

**Comment by may-bee** [comment]
Currently, I am blocked working on #80 as I would have to upgrade all cross-cutting libraries to continue. I would not recommend this for now, due to additional work. More important is the fact, that the sample application should **not** build the modules, but the sample application should **use** the modules!

**Comment by may-bee** [comment]
The current release-task does not work as of the following issue.
I already tried to upgrade minify-css and del dependencies due to my google results, but unfortunately the problem persists....

```
[21:54:58] Starting 'oasp:release'...
[21:54:58] Starting 'sync group5:0'...
[21:54:58] Starting 'build:oasp:init'...
[21:54:58] Finished 'build:oasp:init' after 24 ms
[21:54:58] Finished 'sync group5:0' after 27 ms
[21:54:58] Starting 'sync group5:1'...
[21:54:58] Starting 'clean'...
[21:54:58] 'clean' errored after 3.58 ms
[21:54:58] TypeError: Cannot read property '0' of undefined
    at D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\globby\index.js:16:27
    at Array.forEach (native)
    at sortPatterns (D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\globby\index.js:15:11)
    at module.exports (D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\globby\index.js:43:23)
    at Object.module.exports (D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\del\index.js:31:9)
    at Gulp.<anonymous> (D:\tmp\oasp4js-TYPESCRIPT-DEMO\gulp\build.js:36:14)
    at module.exports (D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\tmp\oasp4js-TYPESCRIPT-DEMO\node_modules\orchestrator\index.js:134:8)
[21:54:58] Finished 'oasp:release' after 38 ms

```
